### ISSUE TITLE
Error in exercise setup?

### ISSUE THREAD

**Issue by tekhaus** [learn-co-students/listening-to-dom-nodes-bootcamp-prep-000#2]
There is no **Open** icon for this exercise, but it requires forking, running tests, and submitting a pull request. Tried manually forking the repo, cloning it to Learn env, running open (it says Lab is a Readme), and running tests (there are none). Ran npm install to no avail.

![screenshot](https://cloud.githubusercontent.com/assets/1009347/18217989/b89db676-7114-11e6-9f2e-8bf224a238dc.png)
![screenshot](https://cloud.githubusercontent.com/assets/1009347/18218042/0ea0b5a0-7115-11e6-835f-ec545970ee8a.png)

**Comment by Zeitlin1** [comment]
I'm running into the same thing tekhaus.  If I figure out a solution I will let you know.

**Comment by tekhaus** [comment]
The temporary workaround is to create a **test** directory in the project folder and then run **learn test**. No tests will pass (since there are none), but none will fail either.
